id: P001786
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN4339
  title: ཐབས་མཁས་པ་ཆེན་པོ་སངས་རྒྱས་དྲིན་ལན་གསབ་པའི་མདོ།
  author: ''
  volumes:
    c291a980a40d457f864528c6f60f90ca:
      image_group_id: I3CN4580
      title: ''
      volume_number: 1
      total_pages: 364
      base_file: v001.txt
